version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18
    commands:
      - php -v
      - composer -V
      - node -v
      - npm -v
      # Install PHP dependencies
      - composer install --no-dev --optimize-autoloader
      # Install Node dependencies
      - npm ci || npm install

  build:
    commands:
      # Build frontend with Vite
      - npm run build
      # Laravel cache/optimizations
      # - php artisan config:cache || true
      # - php artisan route:cache || true
      # - php artisan view:cache || true

artifacts:
  files:
    - app/**/*
    - bootstrap/**/*
    - config/**/*
    - database/**/*
    - public/**/*
    - resources/**/*
    - routes/**/*
    - artisan
    - composer.json
    - composer.lock
    - package.json
    - package-lock.json
    - vite.config.js
    - .platform/**/*
    - .ebextensions/**/*
  base-directory: .
  discard-paths: no
