version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      php: 8.2
    commands:
      - php -v || true
      - composer -V || curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - npm ci --no-audit --progress=false
  build:
    commands:
      - composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader
      - php artisan package:discover || true
      - npm run build
      - test -f public/build/manifest.json || (echo "ERROR: Vite manifest missing" && exit 1)
  post_build:
    commands:
      - rm -rf node_modules

artifacts:
  files:
    - '**/*'
    - '.platform/**/*'
    - '.ebextensions/**/*'
    - 'public/**/*'
    - 'public/.htaccess'
  discard-paths: no
  base-directory: .
