version: 0.2

phases:
  install:
    commands:
      - php -v || true
      - composer -V || curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  build:
    commands:
      - composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader
      - php artisan package:discover || true

artifacts:
  files:
    - '**/*'                 # everything (non-hidden)
    - '.platform/**/*'       # force include hidden EB config
    - '.ebextensions/**/*'   # (if you add any)
    - 'public/**/*'          # make sure public/ goes in
    - 'public/.htaccess'     # explicitly include .htaccess if present
  discard-paths: no
  base-directory: .

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18
    commands:
      - npm install
      - composer install --no-dev --optimize-autoloader
  build:
    commands:
      - npm run build
      - php artisan config:cache
      - php artisan route:cache
artifacts:
  files:
    - '**/*'
