version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18
    commands:
      - composer install --no-dev --optimize-autoloader
      - npm install

  build:
    commands:
      - npm run build
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

artifacts:
  files:
    - '**/*'
  base-directory: .
